### ISSUE TITLE
Out of Memory on pretranslation with 24GB

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine.py#16]
After a job already finetuned a model, the GPU went out-of-memory when pretranslating.  Now, obviously, it takes much more memory to fine tune than pretranslate.  This should be able to be addressed.

https://app.sil.hosted.allegro.ai/projects/9854bf52429e4a0ab630f5e9c547e076/experiments/d235bf0af84e458792e09603cd6bef85/info-output/log?columns=selected&columns=type&columns=name&columns=tags&columns=status&columns=project.name&columns=users&columns=started&columns=last_update&columns=last_iteration&columns=parent.name&order=-last_update&filter=&deep=true
```
[INFO|configuration_utils.py:577] 2023-06-08 08:13:21,623 >> Generate config GenerationConfig {
  "_from_model_config": true,
  "bos_token_id": 0,
  "decoder_start_token_id": 2,
  "eos_token_id": 2,
  "forced_bos_token_id": 256047,
  "max_length": 200,
  "pad_token_id": 1,
  "transformers_version": "4.29.1",
  "use_cache": false
}
Traceback (most recent call last):
  File "/root/.clearml/venvs-builds/3.8/code/untitled.py", line 11, in <module>
    run(args)
  File "/usr/local/lib/python3.8/dist-packages/machine/jobs/build_nmt_engine.py", line 56, in run
    job.run(check_canceled)
  File "/usr/local/lib/python3.8/dist-packages/machine/jobs/nmt_engine_build_job.py", line 68, in run
    _translate_batch(model, pi_batch, writer)
  File "/usr/local/lib/python3.8/dist-packages/machine/jobs/nmt_engine_build_job.py", line 77, in _translate_batch
    for i, result in enumerate(engine.translate_batch(source_segments)):
  File "/usr/local/lib/python3.8/dist-packages/machine/translation/huggingface/hugging_face_nmt_model.py", line 46, in translate_batch
    return self._get_engine().translate_batch(segments)
  File "/usr/local/lib/python3.8/dist-packages/machine/translation/huggingface/hugging_face_nmt_engine.py", line 52, in translate_batch
    return [results[0] for results in self.translate_n_batch(1, segments)]
  File "/usr/local/lib/python3.8/dist-packages/machine/translation/huggingface/hugging_face_nmt_engine.py", line 61, in translate_n_batch
    self._pipeline(segments, num_return_sequences=n),
  File "/usr/local/lib/python3.8/dist-packages/transformers/pipelines/text2text_generation.py", line 367, in __call__
    return super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/pipelines/text2text_generation.py", line 165, in __call__
    result = super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/pipelines/base.py", line 1100, in __call__
    outputs = list(final_iterator)
  File "/usr/local/lib/python3.8/dist-packages/transformers/pipelines/pt_utils.py", line 124, in __next__
    item = next(self.iterator)
  File "/usr/local/lib/python3.8/dist-packages/transformers/pipelines/pt_utils.py", line 125, in __next__
    processed = self.infer(item, **self.params)
  File "/usr/local/lib/python3.8/dist-packages/transformers/pipelines/base.py", line 1025, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "/usr/local/lib/python3.8/dist-packages/machine/translation/huggingface/hugging_face_nmt_engine.py", line 115, in _forward
    output = self.model.generate(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/generation/utils.py", line 1515, in generate
    return self.greedy_search(
  File "/usr/local/lib/python3.8/dist-packages/transformers/generation/utils.py", line 2332, in greedy_search
    outputs = self(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/m2m_100/modeling_m2m_100.py", line 1352, in forward
    lm_logits = self.lm_head(outputs[0])
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 154.00 MiB (GPU 0; 23.68 GiB total capacity; 22.34 GiB already allocated; 25.19 MiB free; 22.48 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
2023-06-08 08:13:29
Process failed, exit code 1
```

**Comment by ddaspit** [comment]
I'm not sure what is happening, but I will try optimizing generation with HF.

**Comment by ddaspit** [comment]
What is the data for the project that ran out of memory? Does this happen consistently? Was the machine being used for anything else at the time?

**Comment by johnml1135** [comment]
I think I figured it out - we don't close the model after we save and before we pretranslate.  Moreover, `HuggingFaceNmtModelTrainer` does not implement the close method.  I believe that should resolve the issue.

https://github.com/sillsdev/machine.py/blob/17c016f9025bd3e922f26175696160a1ba1a7a2d/machine/jobs/nmt_engine_build_job.py#L55-L60

Would this be a good job for @mshannon-sil?
