### ISSUE TITLE
Failing tests: 

### ISSUE THREAD

**Issue by sboisen** [sillsdev/machine.py#8]
I pulled the repo (MacOS), installed the requirements using `poetry`, and ran `poetry run pytest`. That produces these errors, which are unfamiliar to me:

```
poetry run pytest                                                                                                                                                              [7/02/23 | 5:02:53]
========================================================================================= test session starts ==========================================================================================
platform darwin -- Python 3.10.9, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /Users/sboisen/git/sillsdev/machine.py, configfile: pyproject.toml, testpaths: tests
plugins: mockito-0.0.4, typeguard-2.13.3
collected 233 items / 2 errors / 231 selected

================================================================================================ ERRORS ================================================================================================
_____________________________________________________________________ ERROR collecting tests/corpora/test_parallel_text_corpus.py ______________________________________________________________________
tests/corpora/test_parallel_text_corpus.py:4: in <module>
    import pandas as pd
../../../Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/pandas/__init__.py:30: in <module>
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
../../../Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/pandas/_libs/__init__.py:13: in <module>
    from pandas._libs.interval import Interval
pandas/_libs/interval.pyx:1: in init pandas._libs.interval
    ???
E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
__________________________________________________________________ ERROR collecting tests/webapi/test_clearml_nmt_engine_build_job.py __________________________________________________________________
tests/webapi/test_clearml_nmt_engine_build_job.py:22: in <module>
    from machine.webapi.clearml_nmt_engine_build_job import ClearMLNmtEngineBuildJob
machine/webapi/clearml_nmt_engine_build_job.py:6: in <module>
    from clearml import Task
../../../Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/clearml/__init__.py:5: in <module>
    from .task import Task
../../../Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/clearml/task.py:45: in <module>
    from .backend_interface.metrics import Metrics
../../../Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/clearml/backend_interface/__init__.py:2: in <module>
    from .task import Task
../../../Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/clearml/backend_interface/task/__init__.py:1: in <module>
    from .task import Task
../../../Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/clearml/backend_interface/task/task.py:32: in <module>
    from ...binding.artifacts import Artifacts
../../../Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/clearml/binding/artifacts.py:23: in <module>
    from ..backend_interface.metrics.events import UploadEvent
../../../Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/clearml/backend_interface/metrics/__init__.py:3: in <module>
    from .reporter import Reporter
../../../Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/clearml/backend_interface/metrics/reporter.py:19: in <module>
    from ...utilities.plotly_reporter import (
../../../Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/clearml/utilities/plotly_reporter.py:8: in <module>
    import pandas as pd
../../../Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/pandas/__init__.py:30: in <module>
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
../../../Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/pandas/_libs/__init__.py:13: in <module>
    from pandas._libs.interval import Interval
pandas/_libs/interval.pyx:1: in init pandas._libs.interval
    ???
E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
=========================================================================================== warnings summary ===========================================================================================
../../../Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py:10
  /Users/sboisen/Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py:10: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    _nlv = LooseVersion(_np_version)

../../../Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py:11
  /Users/sboisen/Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py:11: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    _np_version_under1p16 = _nlv < LooseVersion("1.16")

../../../Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py:12
  /Users/sboisen/Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py:12: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    _np_version_under1p17 = _nlv < LooseVersion("1.17")

../../../Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py:13
  /Users/sboisen/Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py:13: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    _np_version_under1p18 = _nlv < LooseVersion("1.18")

../../../Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py:14
  /Users/sboisen/Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py:14: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    _np_version_under1p19 = _nlv < LooseVersion("1.19")

../../../Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py:15
  /Users/sboisen/Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py:15: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    _np_version_under1p20 = _nlv < LooseVersion("1.20")

../../../Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/setuptools/_distutils/version.py:345
  /Users/sboisen/Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/setuptools/_distutils/version.py:345: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    other = LooseVersion(other)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================================================================================= short test summary info ========================================================================================
ERROR tests/corpora/test_parallel_text_corpus.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
ERROR tests/webapi/test_clearml_nmt_engine_build_job.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
==================================================================================== 7 warnings, 2 errors in 2.84s =====================================================================================
.-(~/git/sillsdev/machine.py)-------------------------------------------------------------------------------------------------------------------------------------------------------(sboisen@Seans-MBP)-
```

Since it appears to be a pandas/numpy issue, i tried just starting Python and importing pandas, and got a similar error:
```
`--> poetry run python                                                                                                                                                              [7/02/23 | 5:03:05]
Python 3.10.9 (main, Dec 15 2022, 18:18:30) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sboisen/Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/pandas/__init__.py", line 30, in <module>
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
  File "/Users/sboisen/Library/Caches/pypoetry/virtualenvs/sil-machine-oQa04tko-py3.10/lib/python3.10/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
>>>
```

Any insight into what might be going on here, or how i might address it?

**Comment by ddaspit** [comment]
I updated pandas in the main branch. Can you try it out and see if that fixes the problem? Thanks.

**Comment by sboisen** [comment]
As of today, the pandas problem is fixed 👏🏻 
There's another testing error, but i'll open a new issue for that (after i look into it a bit)
